### ISSUE TITLE
BaseSystem is not found directly in pecs_framework

### ISSUE THREAD

**Issue by UplinkPhobia** [krummja/PECS#14]
Hello,

Unlike what the readme says, importing pecs_framework doesn't give access to BaseSystem, and it needs to be imported from pecs_framework.base_system instead.
Not a big deal but I'm guessing it is not intentional.

**Comment by krummja** [comment]
Ah, indeed an oversight. Thanks! Fixed.

**Comment by krummja** [comment]
Ah, indeed an oversight. Thanks! Fixed.
